version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    groups:
      actions:
        patterns:
          - "actions/*"
      typescript-eslint:
        patterns:
          - "@typescript-eslint/*"
      eslint:
        patterns:
          - "eslint*"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
